image: maven:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - build

compile:
  stage: build
  tags:
    - homelab
  artifacts:
    paths:
        - target/*.jar
  script:
    - printenv
    - echo "$MAVEN_REPO_USER"
    - mvn clean install
    - mvn deploy -e -X