image: maven:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2cache/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2cache/repository"

stages:
  - build

compile:
  stage: build
  tags:
    - homelab
  artifacts:
    paths:
        - target/*.jar
  script:
    - mvn clean install -s settings.xml
    - mvn deploy -s settings.xml