image: maven:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/
    - /ssh

variables:
  MAVEN_OPTS: -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2

stages:
  - prepare
  - build
  - deploy

env:
  stage: prepare
  script:
    - mkdir /ssh
    - echo $KEYFILE > /ssh/enc
    - cat /ssh/enc | base64 -d > /ssh/key

compile:
  stage: build
  artifacts:
    paths:
        - target/*.jar
  script:
    - mvn clean
    - mvn install

roll:
  stage: deploy
  only:
    - master
    - integration
  script:
    - git clone git@git.0x09.de:Maven/TestUtil.git -key /ssh/key mvn-repo
    - mvn deploy
    - ls -l

