image: maven:3.6.3-openjdk-16

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - pre
  - build
  - test
  - deploy

versionset:
  stage: pre
  tags:
    - homelab
  script:
    - export versionNumber=$(echo ${CI_COMMIT_BRANCH} | sed -E 's/release\/([0-9a-zA-Z.\\-]+)/\1/')
    - mvn $MAVEN_CLI_OPTS versions:set -DnewVersion=${versionNumber}
  only:
    - release/*
  artifacts:
    paths:
      - pom.xml
    expire_in: 1 day


build:
  stage: build
  tags:
    - homelab
  script:
    - mvn $MAVEN_CLI_OPTS compile
  artifacts:
    paths:
      - pom.xml
      - target/*.jar
    expire_in: 1 day


test:
  stage: test
  tags:
    - homelab
  needs: [ "build" ]
  dependencies:
    - build
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    paths:
      - target/reports/index.html
    expire_in: 1 days
    reports:
      junit:
        - target/reports/TEST-*.xml


deploy:
  stage: deploy
  tags:
    - homelab
  needs: [ "build", "test" ]
  dependencies:
    - build
    - test
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master
    - release/*
