image: maven:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/

variables:
  MAVEN_OPTS: -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2

stages:
  - build
  - deploy

compile:
  stage: build
  tags:
    - homelab
  artifacts:
    paths:
        - target/*.jar
  script:
    - mvn clean install

deploy:
  stage: deploy
  needs: ["compile"]
  tags:
    - homelab
  artifacts:
    paths:
    - target/*.jar
  script:
    - echo "Hello World"
    #- mvn deploy #TODO: setup settings.xml for this project