image: maven:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/

variables:
  MAVEN_OPTS: -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2

stages:
  - prepare
  - build

prepare:
  stage: prepare
  tags:
    - homelab
  script:
    - echo "$MVN_SETTINGS" > "${CI_PROJECT_DIR}/.m2/settings.xml"

compile:
  stage: build
  needs: ["prepare"]
  tags:
    - homelab
  artifacts:
    paths:
        - target/*.jar
  script:
    - mvn clean install
    - mvn mvn deploy